name: step-by-step

services:
  database:
    container_name: step-by-step-database
    build: ./database
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sbs
    volumes:
      - db-data:/var/lib/mysql
  
  frontend:
    container_name: step-by-step-frontend
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

volumes:
  db-data:
