name: step-by-step

services:
  db:
    container_name: step-by-step-db
    build: .
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sbs
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
